[package]
name = "module"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
main_export = { version = "0.1.0", path = "../main_export" }
relib_module = { version = "0", path = "../../../module" }
