[package]
name = "module"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]

[dependencies.relib_module]
version = "0.1.0"
path = "../../../module"
features = ["unloading"]
