[package]
name = "relib"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/xxshady/relib"
readme = "README.md"
rust-version = "1.83.0"
description = "framework for reloading dynamic libraries"

[dependencies]
