[package]
name = "shared_dependency"
version.workspace = true
edition.workspace = true

[dependencies]
shared_dependency_of_dependency = { version = "0.1.0", path = "../shared_dependency_of_dependency" }
