[package]
name = "main_contract"
version.workspace = true
edition.workspace = true

[dependencies]
state = { version = "0.1.0", path = "../state" }
rand = "0.9.2"

[build-dependencies]
cargo_metadata = "0.23.0"
