[workspace] # explicitly excluded from repo workspace

[package]
name = "custom_global_alloc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.relib_module]
version = "0"
path = "../../module"
default-features = false
