name: Test changes

on:
  push:
    branches: "*"

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: ${{ !(startsWith(github.ref, 'refs/tags/v') || endsWith(github.event.head_commit.message, 'wip')) }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
          - os: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: rust version
        run: rustc -V

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: build workspace without default features
        run: cargo build --workspace --no-default-features

      # doesn't work due to multiple identical symbol exports (main fn and before_unload) in test module
      # - name: build workspace with all features
      #   run: cargo build --workspace --all-features
      - name: check workspace with all features
        run: cargo check --workspace --all-features

      - name: clippy
        run: cargo clippy --workspace

      - name: check examples
        run: |
          cd examples/template

          cargo add relib_module --path ../../module --package module
          cargo add relib_host --path ../../host --package host
          cargo rm relib_interface --package host
          cargo rm relib_interface --package host --build
          cargo add relib_interface --path ../../interface --package host --features include
          cargo add relib_interface --path ../../interface --package host --features build --build
          cargo rm relib_interface --package module
          cargo rm relib_interface --package module --build
          cargo add relib_interface --path ../../interface --package module --features include
          cargo add relib_interface --path ../../interface --package module --features build  --build
          cargo build --workspace
          cargo clippy --workspace
          cargo build --workspace --features unloading
          cargo clippy --workspace --features unloading

          cd ../abi_stable_usage
          cargo build --workspace
          cargo clippy --workspace
          cargo build --workspace --features unloading
          cargo clippy --workspace --features unloading

          cd ../custom_global_alloc
          cargo build --workspace
          cargo clippy --workspace
          cargo build --workspace --features unloading
          cargo clippy --workspace --features unloading

          cd ../live_reload
          cargo build --workspace
          cargo clippy --workspace

          cd ../live_reload_extended
          cargo build --workspace
          cargo clippy --workspace

          cd ../hot_reload
          cargo build --workspace
          cargo clippy --workspace

          cd ../export_main_macro
          cargo build --workspace
          cargo clippy --workspace

          cd ../different_interfaces
          cargo build --workspace
          cargo clippy --workspace
          cargo build --workspace --features unloading
          cargo clippy --workspace --features unloading

      - name: test runner
        run: cargo run --bin test_runner
